package springBoot;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import java.util.Map;

/**
 * Created by Vladimir on 20.04.2020.
 */
@Controller
public class UserController {
    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private final UserRepository userRepository;

    @Autowired
    public UserController(UserRepository userRepository) {
        this.userRepository = userRepository;
    }

    @GetMapping(path="/allUsers")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }

    @GetMapping()
    public String root() {
        return "loginSuccess";
    }

    @GetMapping(path="/registration")
    public String registration() {
        return "registration";
    }

    @PostMapping(path="/registration")
    public String addNewUser (User user, Map<String, Object> model) {
        User userByName = userRepository.findByName(user.getName());

        if(userByName != null) {
            model.put("message", "User already exist!");
            return "registration";
        }

        userRepository.save(user);
        return "redirect:/login";
    }
}
