package springBoot.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;
import springBoot.domain.User;
import springBoot.repository.UserRepository;

/**
 * Created by Vladimir on 20.04.2020.
 */
@RestController
@RequestMapping(UserController.REST_URL)
@PreAuthorize("hasAuthority('ADMIN')")
public class UserController {
    static final String REST_URL = "/users";

    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private final UserRepository userRepository;

    @Autowired
    public UserController(UserRepository userRepository) {
        this.userRepository = userRepository;
    }

    @GetMapping
    public Iterable<User> getAllUsers() {
        return userRepository.findAll();
    }

    @GetMapping("/{id}")
    public User getUserForEdit(@PathVariable int id) {
        return userRepository.findById(id);
    }

    @PostMapping("/{id}")
    public User update(@PathVariable("id") User user, @RequestBody User updatedUser) {
        user.setName(updatedUser.getName());
        user.setRoles(updatedUser.getRoles());
        return userRepository.save(user);
    }
}
