package springBoot.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;
import springBoot.domain.User;
import springBoot.service.UserService;

/**
 * Created by Vladimir on 20.04.2020.
 */
@RestController
@RequestMapping(UserController.REST_URL)
@PreAuthorize("hasAuthority('ADMIN')")
public class UserController {
    static final String REST_URL = "/users";

    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private final UserService userService;

    @Autowired
    public UserController(UserService userService) {
        this.userService = userService;
    }

    @GetMapping
    public Iterable<User> getAllUsers() {
        return userService.getAll();
    }

    @GetMapping("/{id}")
    public User getUser(@PathVariable int id) {
        return userService.get(id);
    }

    @PostMapping("/{id}")
    public User update(@PathVariable("id") User user, @RequestBody User updatedUser) {
        return userService.update(user, updatedUser);
    }
}
